language: java

sudo: true

cache:
  directories:
    - $HOME/.m2

before_cache:
  - rm -rf $HOME/.m2/repository/org/sistcoop

jdk:
  - oraclejdk8

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y gnupg2

script: mvn --settings .travis/settings.xml clean  verify

deploy:
  -
      provider: script
      script: .travis/deploy.sh
      skip_cleanup: true
      on:
        repo: openfact/openfact
        branch: master
        jdk: oraclejdk8
  -
    provider: script
    script: .travis/deploy.sh
    skip_cleanup: true
    on:
      repo: openfact/openfact
      tags: true
      jdk: oraclejdk8


notifications:
  email:
    - carlosthe19916@gmail.com