language: java
sudo: false
install: true
dist: trusty
cache:
  directories:
  - $HOME/.m2/repository
  - $HOME/.sonar/cache
jdk:
- oraclejdk8
addons:
  sonarqube: true
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar -e
notifications:
  email: false
env:
  global:
    secure: aMLZ+6Oe0kC/I6oFyFS+USfnfLeSd0mIr9KXIxtLQygJckjuKf2bVZnWFw9Cr/mK+nF+e/FSDRoKr25coQEuxUari9x1WMmShaM1Txw8TfEsd4gOA4kWjIX0wc8OyXMxNVxc9q3Un5q0/8a2GlNVwrGLZ337RewOVblpggecqFdEqXTv3w8yDwIWn0e1/u5dS2SX1kU9kWPoQaBMThL21a0Wtvt/FNtg1G39U8fkGrTgLXR5x7uBJpmzqPaY6NMazDWZOYscP+6m441j4aGecj1r34lkTH9sW5HctdRLu5HDo1vKXjd3PoAF9HZeD51ZrJdgJKj/DlZgt872peVWFERysGecDM/OF2zcICIHvqLpDdQqjsn3aVI0QO9TF7mzWvuFAg887ZFxPN3O2ayRijXXipSnDodEixwKJpoJJZHc+ZEN0e7FNywxGrpVbYK5HRYaeOW1+RK1bK/8+dpOCzZ0j/InUzbOK8fwHXWZl3VxY5EHn8zuK8jDcqAyLPbjJuFk1ynT23Spst4N/8J0/+7HdFlhPax2KbOca4arQhkRmyEUb2TOdMxUxcJe7id2kS1YCbO303CvOo50hYdZcnULUo52iPFqYWQuKBcHMKldkPVYBJ4TJNvt9lQBMsCder1+t2++CV3mEPV4HJHKW4awJCcpch6gjm8SQdyD/2k=
