language: java
sudo: false
install: true
dist: trusty
addons:
  sonarqube:
    token:
      secure: Tm52p/ApmuJw/iC1IYjBUHFP9Rc0+VE6SxbRiy93l9HFHgfCeSBb1SCn5ezVLwOykM6pvCggjeyxpj9UaSmcTg6w1yTwiusGRl6IJ/RrqdsA902Ct3/jTuMui0yr3wYWVqmt6BWuytlZ6XaFnDCUecG+3qJvMPEdTUysplUYO0TfF8omvyS8fiuNK9LMPMCHmTeWj70RcIJnebieRYc1H8lYCCOZy6XW4sUXZm6LgILaVoMfMeZ92EwGfJe+1HN7cQJrCdb6jpHrCizPfVVMd1ccc9xbu4mIx5IE2UV1zcCh/aIjIRx4O7uPkIEhXowwx7UdmSKKu2Sn6fIZFTQiDWH4gqFp9HURP6xM5mKUv6ACgP0TYsit6sm1G1ylycypymxjCcjqDyJ3Xx1WwseB7qzN9V/IXV07b7oP/8UxUsSBWlWBk9RTvjGqA0CG/iWoKY2XZl7H6eVSa5czcrRYKq1+q12pizGkz3QFltJgkWJwUQprW4/cDTqilGp4wyxzFepjgKHpXNYnykUv3ST3lm0TWdmSGcWxvYEP4nw9UxKWEr6TUJsN1uZ0Fbf1dYeSMFxtu+C7j8Il/u9ZBbrAqmPg/1WFwLMFf8tNCK6LMr59Ttt6Qi5kagwlJ2IC2zWIDhQK+o6M4AR5BJJANauFjOFynIhmaELtOvFpxS/VhA4=
cache:
  directories:
  - $HOME/.m2/repository
  - $HOME/.sonar/cache
jdk:
- oraclejdk8
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
notifications:
  email: false
env:
  global:
    secure: Tm52p/ApmuJw/iC1IYjBUHFP9Rc0+VE6SxbRiy93l9HFHgfCeSBb1SCn5ezVLwOykM6pvCggjeyxpj9UaSmcTg6w1yTwiusGRl6IJ/RrqdsA902Ct3/jTuMui0yr3wYWVqmt6BWuytlZ6XaFnDCUecG+3qJvMPEdTUysplUYO0TfF8omvyS8fiuNK9LMPMCHmTeWj70RcIJnebieRYc1H8lYCCOZy6XW4sUXZm6LgILaVoMfMeZ92EwGfJe+1HN7cQJrCdb6jpHrCizPfVVMd1ccc9xbu4mIx5IE2UV1zcCh/aIjIRx4O7uPkIEhXowwx7UdmSKKu2Sn6fIZFTQiDWH4gqFp9HURP6xM5mKUv6ACgP0TYsit6sm1G1ylycypymxjCcjqDyJ3Xx1WwseB7qzN9V/IXV07b7oP/8UxUsSBWlWBk9RTvjGqA0CG/iWoKY2XZl7H6eVSa5czcrRYKq1+q12pizGkz3QFltJgkWJwUQprW4/cDTqilGp4wyxzFepjgKHpXNYnykUv3ST3lm0TWdmSGcWxvYEP4nw9UxKWEr6TUJsN1uZ0Fbf1dYeSMFxtu+C7j8Il/u9ZBbrAqmPg/1WFwLMFf8tNCK6LMr59Ttt6Qi5kagwlJ2IC2zWIDhQK+o6M4AR5BJJANauFjOFynIhmaELtOvFpxS/VhA4=
