language: java
sudo: false
install: true
dist: trusty
cache:
  directories:
  - $HOME/.m2/repository
  - $HOME/.sonar/cache
jdk:
- oraclejdk8
addons:
  sonarqube:
    token:
      secure: $SONAR_TOKEN
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar -e
notifications:
  email: false
env:
  global:
    secure: H4Vfnzmwr6hfP6kFbI/Z3gknpfiHjLbrjAxWe2tNeQYAuvwGOZS1YuI+LE9ioINLuMUYbaZvbdKb+wURyua/zoJzt87JillEdtz/fCINjoCzBhv2D8Gi18MrOhADMe5xWKGWJH+AnK5jtrR89haTXA9LQLETacfkiSFdcyeXP07MqbpCBeyEaDL/GFTbUOCL8X3Ntwcu6Zfe4kzSkLUjs2gf8VdSwAFF3u/ivIVyF0bBWjp9osUqt2GUGdTaYFfhb9Z5t3xzscYG5rGLbd8CmZkVELQgkrQZEEegMSnuNL4TyBoOaQ7GJB5xzfE6tMSRngpl6aa+UQzK/V5mrlh5sxAu0r0oWnU/N/iMOFj2D3tf+nl8uy1223L8PxLngPE/p0NpgWv9pD8Re6HrLC5BZ3Sd4E196eXyY3PmZbFIDYopU3yQaoRtJSc2rknHS8verlQ/8XJk2Vn2vxWVjWJrIsLc+t3/wQJJ8VwJ1Wc9QRyRHVkHSsozTsfCzid5tZb8R1Vk5AjzhfDwtRwazPG/5kuwKV/6kYUtt3Ia2Qwn3PDrYxJMi9NN11At/QRMZ24spSOxYt5Hg53eUyF3xwNuwOadGPO/ijSGOTAfIDeesHY9HMNwiwt0GNMiM+CCjoX21kA1CTLhTraICVee68HT5rUxobp04kwnO+jl51bvAqw=
