language: java
sudo: false
install: true
dist: trusty
cache:
  directories:
  - $HOME/.m2/repository
  - $HOME/.sonar/cache
jdk:
- oraclejdk8
addons:
  sonarqube:
    token: $SONAR_TOKEN
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar -e -Dsonar.login=$SONAR_TOKEN
notifications:
  email: false
