language: java

cache:
  directories:
    - $HOME/.m2

before_cache:
  - rm -rf $HOME/.m2/repository/org/sistcoop

jdk:
  - oraclejdk8

install:
  - mvn --settings .travis/settings.xml install -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=true -B -V
  
script: mvn --settings .travis/settings.xml clean  verify

deploy:
  -
    provider: script
    script: .travis/deploy.sh
    skip_cleanup: true
    on:
      repo: openfact/openfact
      tags: true
      jdk: oraclejdk8


notifications:
  email:
    - carlosthe19916@gmail.com